embeddings {
  tensor_name: "spot_id:01250"
  metadata_path: "01250/spot_id/metadata.tsv"
  tensor_path: "01250/spot_id/tensors.tsv"
}
embeddings {
  tensor_name: "vehicle_type:01250"
  metadata_path: "01250/vehicle_type/metadata.tsv"
  tensor_path: "01250/vehicle_type/tensors.tsv"
}
embeddings {
  tensor_name: "region_code:01250"
  metadata_path: "01250/region_code/metadata.tsv"
  tensor_path: "01250/region_code/tensors.tsv"
}
embeddings {
  tensor_name: "dow:01250"
  metadata_path: "01250/dow/metadata.tsv"
  tensor_path: "01250/dow/tensors.tsv"
}
embeddings {
  tensor_name: "week:01250"
  metadata_path: "01250/week/metadata.tsv"
  tensor_path: "01250/week/tensors.tsv"
}
embeddings {
  tensor_name: "month:01250"
  metadata_path: "01250/month/metadata.tsv"
  tensor_path: "01250/month/tensors.tsv"
}
embeddings {
  tensor_name: "quarter:01250"
  metadata_path: "01250/quarter/metadata.tsv"
  tensor_path: "01250/quarter/tensors.tsv"
}
embeddings {
  tensor_name: "is_weekend:01250"
  metadata_path: "01250/is_weekend/metadata.tsv"
  tensor_path: "01250/is_weekend/tensors.tsv"
}
embeddings {
  tensor_name: "is_holiday:01250"
  metadata_path: "01250/is_holiday/metadata.tsv"
  tensor_path: "01250/is_holiday/tensors.tsv"
}
